apiVersion: v1
kind: Service
metadata:
  name: {{ template "google-pgbouncer.ilb.name" . }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: {{ template "google-pgbouncer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: tcp-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
