apiVersion: v1
kind: Service
metadata:
  name: {{ include "google-pgbouncer.fullname" . }}
  labels:
    {{- include "google-pgbouncer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    app.kubernetes.io/name: {{ template "google-pgbouncer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
