{{- if not .Values.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "google-pgbouncer.serviceAccountName" . }}
  labels:
    {{- include "google-pgbouncer.labels" . | nindent 4 }}
  {{ if .Values.serviceAccount.annotations -}}
  annotations: {{ .Values.serviceAccount.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
{{- end }}
