apiVersion: v1
kind: Secret
metadata:
  name: {{ template "google-pgbouncer.fullname" . }}-userlist-secret
  labels:
    {{- include "google-pgbouncer.labels" . | nindent 4 }}
data:
  userlist.txt: {{ include "google-pgbouncer.secret.userlist" . | trim | b64enc }}
