apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer-container.fullname" . }}-userlist-secret
  labels:
    {{- include "pgbouncer-container.labels" . | nindent 4 }}
data:
  userlist.txt: {{ include "pgbouncer-container.secret.userlist" . | trim | b64enc }}
