apiVersion: v1
kind: Service
metadata:
  name: ilb-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  namespace: pgb-namespace
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: google-pgbouncer
    app.kubernetes.io/instance: google-pgbouncer
  ports:
  - name: tcp-port
    protocol: TCP
    port: 5432
    targetPort: 5432
